name: Build PR Documentation

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_documentation:
    runs-on: ubuntu-20.04
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.number }}
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
      PR_CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'huggingface/doc-builder'
          path: doc-builder

      - uses: actions/checkout@v4
        with:
          repository: 'huggingface/optimum-executorch'
          path: optimum-executorch

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache-dependency-path: "kit/package-lock.json"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup environment
        run: |
          pip install --upgrade pip
          pip uninstall -y doc-builder
          cd doc-builder
          git pull origin main
          pip install .
          cd ../optimum-executorch
          pip install .[quality]

      - name: Make documentation
        shell: bash
        run: |
          cd optimum-executorch
          doc-builder build optimum.executorch docs/source/ \
            --repo_name optimum-executorch \
            --build_dir executorch-doc-build/ \
            --version pr_${{ env.PR_NUMBER }} \
            --version_tag_suffix "" \
            --html \
            --clean \

      - name: Save commit_sha & pr_number
        run: |
          cd optimum-executorch
          sudo chmod -R ugo+rwx executorch-doc-build
          cd executorch-doc-build
          sudo mv optimum.executorch optimum-executorch
          echo ${{ env.COMMIT_SHA }} > ./commit_sha
          echo ${{ env.PR_NUMBER }} > ./pr_number

      - uses: actions/upload-artifact@v4
        with:
          name: doc-build-artifact
          path: executorch-doc-build/